#!/usr/bin/env python3
"""Generate Unity-style .csproj/.sln from Bee .rsp files for Cursor IntelliSense."""
from __future__ import annotations

import glob
import os
import re
import uuid
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DAG = ROOT / "Library" / "Bee" / "artifacts" / "1900b0aE.dag"

# Assemblies needed for navigating this project's package code
WANTED = [
    "UnityQemu",
    "UnityQemu.Editor",
    "TriInspector",
    "TriInspector.Editor",
    "Assembly-CSharp",
    "Assembly-CSharp-Editor",
    "Unity.VisualStudio.Editor",
]


def parse_rsp(rsp_path: Path) -> dict:
    defines: list[str] = []
    refs: list[str] = []
    sources: list[str] = []
    analyzers: list[str] = []
    lang = "9.0"
    unsafe = False
    for raw in rsp_path.read_text(encoding="utf-8", errors="replace").splitlines():
        line = raw.strip()
        if not line:
            continue
        if line.startswith("-define:"):
            defines.append(line[len("-define:") :])
        elif line.startswith("-r:") or line.startswith("/r:") or line.startswith("-reference:"):
            ref = line.split(":", 1)[1].strip().strip('"')
            refs.append(ref)
        elif line.startswith("-analyzer:") or line.startswith("/analyzer:"):
            analyzers.append(line.split(":", 1)[1].strip().strip('"'))
        elif line.startswith("-langversion:"):
            lang = line.split(":", 1)[1].strip()
        elif line in ("-unsafe", "/unsafe"):
            unsafe = True
        elif line.startswith('"') and line.endswith('.cs"'):
            sources.append(line.strip('"').replace("/", "\\"))
        elif line.endswith(".cs") and not line.startswith("-"):
            sources.append(line.strip('"').replace("/", "\\"))
    # Bee .rsp can lag behind the asset database; include sibling .cs files on disk.
    source_dirs = {str(Path(s).parent) for s in sources}
    merged = set(sources)
    for d in source_dirs:
        folder = ROOT / d.replace("\\", "/")
        if not folder.is_dir():
            continue
        for cs in folder.rglob("*.cs"):
            rel = cs.relative_to(ROOT).as_posix().replace("/", "\\")
            merged.add(rel)
    sources = sorted(merged)

    return {
        "defines": defines,
        "refs": refs,
        "sources": sources,
        "analyzers": analyzers,
        "lang": lang,
        "unsafe": unsafe,
    }


def guid_for(name: str) -> str:
    return str(uuid.uuid5(uuid.NAMESPACE_URL, f"unityqemu/{name}")).upper()


def write_csproj(name: str, data: dict, project_refs: list[str]) -> Path:
    defines = ";".join(data["defines"] + ["DEBUG", "TRACE"])
    compile_items = "\n".join(
        f'    <Compile Include="{s}" />' for s in data["sources"]
    )
    # Prefer project references for WANTED assemblies; otherwise HintPath
    wanted_dll = {f"{n}.dll" for n in WANTED}
    ref_items: list[str] = []
    for ref in data["refs"]:
        base = os.path.basename(ref)
        stem = Path(base).stem
        if stem in project_refs:
            continue  # project reference instead
        # Skip self
        if stem == name:
            continue
        hint = ref.replace("/", "\\")
        ref_items.append(
            "    <Reference Include=\"{0}\">\n"
            "      <HintPath>{1}</HintPath>\n"
            "      <Private>False</Private>\n"
            "    </Reference>".format(stem, hint)
        )
    references = "\n".join(ref_items)

    proj_ref_xml = "\n".join(
        "    <ProjectReference Include=\"{0}.csproj\">\n"
        "      <Project>{{{1}}}</Project>\n"
        "      <Name>{0}</Name>\n"
        "    </ProjectReference>".format(pr, guid_for(pr))
        for pr in project_refs
        if pr != name
    )

    analyzer_xml = "\n".join(
        f'    <Analyzer Include="{a.replace("/", chr(92))}" />' for a in data["analyzers"]
    )

    xml = f"""<Project ToolsVersion="Current">
  <!-- Generated by Tools/generate_csproj_from_rsp.py for Cursor Go to Definition -->
  <PropertyGroup>
    <BaseIntermediateOutputPath>Temp\\obj\\$(Configuration)\\$(MSBuildProjectName)</BaseIntermediateOutputPath>
    <IntermediateOutputPath>$(BaseIntermediateOutputPath)</IntermediateOutputPath>
  </PropertyGroup>
  <Import Project="Sdk.props" Sdk="Microsoft.NET.Sdk" />
  <ItemGroup>
    <ProjectCapability Include="Unity" />
  </ItemGroup>
  <PropertyGroup>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <EnableDefaultItems>false</EnableDefaultItems>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <LangVersion>{data["lang"]}</LangVersion>
    <Configurations>Debug;Release</Configurations>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
    <RootNamespace></RootNamespace>
    <OutputType>Library</OutputType>
    <AssemblyName>{name}</AssemblyName>
    <TargetFramework>netstandard2.1</TargetFramework>
    <BaseDirectory>.</BaseDirectory>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>Temp\\bin\\Debug\\</OutputPath>
    <DefineConstants>{defines}</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <NoWarn>0169;USG0001</NoWarn>
    <AllowUnsafeBlocks>{str(data["unsafe"]).lower()}</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup>
    <NoStandardLibraries>true</NoStandardLibraries>
    <NoStdLib>true</NoStdLib>
    <NoConfig>true</NoConfig>
    <DisableImplicitFrameworkReferences>true</DisableImplicitFrameworkReferences>
    <MSBuildWarningsAsMessages>MSB3277</MSBuildWarningsAsMessages>
  </PropertyGroup>
  <PropertyGroup>
    <UnityProjectGenerator>Package</UnityProjectGenerator>
    <UnityProjectGeneratorVersion>2.0.26</UnityProjectGeneratorVersion>
    <UnityProjectGeneratorStyle>SDK</UnityProjectGeneratorStyle>
    <UnityProjectType>Game:1</UnityProjectType>
    <UnityBuildTarget>StandaloneWindows64:19</UnityBuildTarget>
    <UnityVersion>6000.3.19f1</UnityVersion>
  </PropertyGroup>
  <ItemGroup>
{analyzer_xml}
  </ItemGroup>
  <ItemGroup>
{compile_items}
  </ItemGroup>
  <ItemGroup>
{references}
  </ItemGroup>
  <ItemGroup>
{proj_ref_xml}
  </ItemGroup>
  <Import Project="Sdk.targets" Sdk="Microsoft.NET.Sdk" />
</Project>
"""
    out = ROOT / f"{name}.csproj"
    out.write_text(xml, encoding="utf-8")
    return out


def write_sln(projects: list[str]) -> Path:
    configs = []
    entries = []
    for name in projects:
        g = guid_for(name)
        entries.append(
            f'Project("{{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}}") = "{name}", "{name}.csproj", "{{{g}}}"\nEndProject'
        )
        configs.append(
            f"\t\t{{{g}}}.Debug|Any CPU.ActiveCfg = Debug|Any CPU\n"
            f"\t\t{{{g}}}.Debug|Any CPU.Build.0 = Debug|Any CPU\n"
            f"\t\t{{{g}}}.Release|Any CPU.ActiveCfg = Release|Any CPU\n"
            f"\t\t{{{g}}}.Release|Any CPU.Build.0 = Release|Any CPU"
        )
    sln = f"""Microsoft Visual Studio Solution File, Format Version 12.00
# Visual Studio 15
{chr(10).join(entries)}
Global
	GlobalSection(SolutionConfigurationPlatforms) = preSolution
		Debug|Any CPU = Debug|Any CPU
		Release|Any CPU = Release|Any CPU
	EndGlobalSection
	GlobalSection(ProjectConfigurationPlatforms) = postSolution
{chr(10).join(configs)}
	EndGlobalSection
EndGlobal
"""
    out = ROOT / "unityqemu.sln"
    out.write_text(sln, encoding="utf-8")
    return out


def main() -> None:
    if not DAG.is_dir():
        raise SystemExit(f"Bee dag not found: {DAG}")

    available = []
    for name in WANTED:
        rsp = DAG / f"{name}.rsp"
        if rsp.is_file():
            available.append(name)
        else:
            print(f"skip missing rsp: {name}")

    # Project refs: Editor -> Runtime, TriInspector.Editor -> TriInspector, etc.
    pref_map = {
        "UnityQemu.Editor": ["UnityQemu"],
        "TriInspector.Editor": ["TriInspector"],
        "Assembly-CSharp-Editor": ["Assembly-CSharp"],
    }

    for name in available:
        data = parse_rsp(DAG / f"{name}.rsp")
        prefs = [p for p in pref_map.get(name, []) if p in available]
        path = write_csproj(name, data, prefs)
        print(f"wrote {path.name} ({len(data['sources'])} sources)")

    sln = write_sln(available)
    print(f"wrote {sln.name} with {len(available)} projects")


if __name__ == "__main__":
    main()
